### ISSUE TITLE
Why is there no support for 'page' post-type?

### ISSUE THREAD

**Issue by pepsiftd** [JoaquimInteresting/rest-api-comment#1]
public\class-rest-api-comment-public.php line 118
`if ( empty( $post ) || empty( $post->ID ) || 'post' !== $post->post_type ) {`

When trying to comment on a 'page' post-type this line makes the plugin return a '404' status.
Why not let it be like 
`if ( empty( $post ) || empty( $post->ID ) || ('post' !== $post->post_type && 'page' !== $post->post_type) ) {`
?
Using this line enables commenting on 'page' post types.

**Comment by JoaquimInteresting** [comment]
Well this plugin was created to allow only comments for 'Posts' through the rest api, reason why it does not support comments for pages.

**Comment by pepsiftd** [comment]
Ok I see.
But is there anything special about commenting 'page' post-type compared to 'post'?
I don't see any difference. For me it looks like you could just allow that post-type and it would magically work, wouldn't it?
